-- Create Database
CREATE DATABASE IF NOT EXISTS product_marketing;
USE product_marketing;

-- 1. Add 'role' column to users table
ALTER TABLE users ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'customer';

-- 2. Insert an initial admin user
-- IMPORTANT: You MUST replace 'YOUR_HASHED_PASSWORD' with a hash generated by your Flask application's security utility (e.g., generate_password_hash('adminpassword')).
-- If you don't, the admin user will not be able to log in.
INSERT INTO users (name, email, password, phone, address, role) VALUES 
('Admin User', 'admin@example.com', 'YOUR_HASHED_PASSWORD', '00000000000', 'Admin Office', 'admin');

-- 3. Update existing users to ensure they are marked as 'customer'
UPDATE users SET role = 'customer' WHERE role IS NULL;

-- Users Table
CREATE TABLE IF NOT EXISTS users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(11) NOT NULL,
    address TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Categories Table
CREATE TABLE IF NOT EXISTS categories (
    category_id INT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Products Table
CREATE TABLE IF NOT EXISTS products (
    product_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    stock_quantity INT NOT NULL DEFAULT 0,
    category_id INT,
    image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(category_id) ON DELETE SET NULL
);

-- Cart Table
CREATE TABLE IF NOT EXISTS cart (
    cart_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE,
    UNIQUE KEY unique_user_product (user_id, product_id)
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
    order_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) DEFAULT 'Pending',
    total_amount DECIMAL(10, 2) NOT NULL,
    shipping_address TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Order_Items Table
CREATE TABLE IF NOT EXISTS order_items (
    order_item_id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    price_at_purchase DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE
);

-- Clear existing data (optional - comment out if you want to keep existing data)
-- DELETE FROM order_items;
-- DELETE FROM orders;
-- DELETE FROM cart;
-- DELETE FROM products;
-- DELETE FROM categories;
-- DELETE FROM users;

-- Insert Sample Categories
INSERT IGNORE INTO categories (category_name) VALUES 
('Electronics'), 
('Clothing'), 
('Books'), 
('Home & Garden'),
('Sports'),
('Toys & Games'),
('Beauty & Health'),
('Automotive'),
('Food & Beverages'),
('Office Supplies');

-- Insert Sample Products (Extended List)
INSERT INTO products (name, description, price, stock_quantity, category_id, image_url) VALUES
-- Electronics (Category 1)
('Laptop Pro 15', 'High-performance laptop with 16GB RAM and 512GB SSD', 1299.99, 25, 1, 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400'),
('Wireless Mouse', 'Ergonomic wireless mouse with precision tracking', 29.99, 150, 1, 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400'),
('Smart Phone X', 'Latest smartphone with 5G connectivity and dual camera', 899.99, 50, 1, 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400'),
('Bluetooth Headphones', 'Noise-cancelling wireless headphones with 30hr battery', 149.99, 80, 1, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400'),
('4K Monitor 27"', 'Ultra HD 4K monitor with HDR support', 449.99, 35, 1, 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400'),
('Mechanical Keyboard', 'RGB mechanical gaming keyboard with blue switches', 89.99, 60, 1, 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400'),
('Portable SSD 1TB', 'Fast external SSD with USB-C connection', 119.99, 70, 1, 'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=400'),
('Gaming Laptop 17', 'High-end gaming laptop with RTX graphics and 32GB RAM', 1899.99, 15, 1, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400'),
('USB-C Hub', '7-in-1 USB-C hub with HDMI and card reader', 49.99, 120, 1, 'https://images.unsplash.com/photo-1611078489935-0cb964de46d6?w=400'),
('Noise Cancelling Earbuds', 'True wireless earbuds with active noise cancellation', 129.99, 85, 1, 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400'),
('Smart Home Camera', 'WiFi security camera with night vision', 79.99, 60, 1, 'https://images.unsplash.com/photo-1558002038-1055907df827?w=400'),
('Portable Projector', 'Mini HD projector for home entertainment', 199.99, 40, 1, 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400'),

-- Clothing (Category 2)
('Cotton T-Shirt', 'Comfortable 100% cotton t-shirt in multiple colors', 19.99, 200, 2, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400'),
('Denim Jeans', 'Classic blue denim jeans with regular fit', 49.99, 100, 2, 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400'),
('Leather Jacket', 'Premium genuine leather jacket for men', 199.99, 30, 2, 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400'),
('Summer Dress', 'Floral print summer dress for women', 59.99, 75, 2, 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400'),
('Sneakers', 'Casual comfortable sneakers for everyday wear', 79.99, 90, 2, 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400'),
('Hoodie', 'Warm fleece hoodie with front pocket', 39.99, 120, 2, 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400'),
('Formal Shirt', 'Slim-fit formal shirt for office wear', 34.99, 140, 2, 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400'),
('Winter Sweater', 'Warm wool sweater for cold weather', 54.99, 90, 2, 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400'),
('Sports Shorts', 'Breathable sports shorts for workouts', 24.99, 160, 2, 'https://images.unsplash.com/photo-1593032465175-481ac7f401a0?w=400'),
('Leather Belt', 'Genuine leather belt with metal buckle', 29.99, 110, 2, 'https://images.unsplash.com/photo-1622560480654-d96214fdc887?w=400'),
('Wool Scarf', 'Soft wool scarf for winter fashion', 27.99, 95, 2, 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=400'),

-- Books (Category 3)
('Python Programming', 'Complete guide to Python programming for beginners', 39.99, 80, 3, 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400'),
('Fiction Novel', 'Best-selling fiction novel of the year', 14.99, 120, 3, 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400'),
('Web Development Guide', 'Learn modern web development from scratch', 44.99, 65, 3, 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400'),
('Cookbook', 'Delicious recipes for home cooking', 29.99, 55, 3, 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400'),
('Self-Help Book', 'Transform your life with proven strategies', 19.99, 95, 3, 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400'),
('Data Science Handbook', 'Comprehensive guide to data science concepts', 49.99, 70, 3, 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400'),
('AI for Beginners', 'Easy introduction to artificial intelligence', 29.99, 100, 3, 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400'),
('Business Management', 'Modern business management strategies', 39.99, 60, 3, 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400'),
('Data Science Handbook', 'Comprehensive guide to data science concepts', 49.99, 70, 3, 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400'),
('AI for Beginners', 'Easy introduction to artificial intelligence', 29.99, 100, 3, 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400'),
('Business Management', 'Modern business management strategies', 39.99, 60, 3, 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400'),

-- Home & Garden (Category 4)
('Garden Tools Set', 'Complete set of essential gardening tools', 79.99, 40, 4, 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'),
('LED Desk Lamp', 'Adjustable LED desk lamp with USB charging port', 34.99, 90, 4, 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400'),
('Coffee Maker', 'Programmable coffee maker with timer function', 89.99, 50, 4, 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=400'),
('Throw Pillows Set', 'Decorative throw pillows set of 4', 39.99, 85, 4, 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=400'),
('Indoor Plant Pot', 'Ceramic plant pot with drainage tray', 24.99, 100, 4, 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400'),
('Blender', 'High-speed blender for smoothies and shakes', 69.99, 45, 4, 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=400'),
('Vacuum Cleaner', 'Bagless vacuum cleaner with HEPA filter', 149.99, 30, 4, 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400'),
('Wall Clock', 'Modern silent wall clock', 29.99, 85, 4, 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400'),
('Bedside Table Lamp', 'Minimalist bedside lamp with warm light', 44.99, 65, 4, 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400'),

-- Sports (Category 5)
('Yoga Mat', 'Premium non-slip yoga mat with carrying strap', 24.99, 75, 5, 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400'),
('Running Shoes', 'Lightweight running shoes for maximum comfort', 89.99, 60, 5, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400'),
('Basketball', 'Official size and weight basketball', 29.99, 100, 5, 'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=400'),
('Dumbbells Set', 'Adjustable dumbbells set 5-25lbs', 149.99, 35, 5, 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400'),
('Tennis Racket', 'Professional tennis racket with case', 79.99, 40, 5, 'https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=400'),
('Fitness Tracker', 'Smart fitness tracker with heart rate monitor', 59.99, 65, 5, 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400'),
('Jump Rope', 'Adjustable jump rope for cardio workouts', 14.99, 150, 5, 'https://images.unsplash.com/photo-1607962837359-5e7e89f86776?w=400'),
('Gym Gloves', 'Anti-slip gym gloves for weight training', 19.99, 110, 5, 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=400'),

-- Toys & Games (Category 6)
('Puzzle 1000 Pieces', 'Challenging jigsaw puzzle with beautiful artwork', 19.99, 85, 6, 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400'),
('Building Blocks Set', 'Creative building blocks set 500+ pieces', 49.99, 60, 6, 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400'),
('Remote Control Car', 'High-speed RC car with rechargeable battery', 79.99, 45, 6, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400'),
('Action Figure', 'Superhero action figure collectible', 24.99, 95, 6, 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=400'),

-- Beauty & Health (Category 7)
('Skincare Set', 'Complete skincare routine set for all skin types', 89.99, 55, 7, 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400'),
('Hair Dryer', 'Professional ionic hair dryer with diffuser', 69.99, 40, 7, 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400'),
('Electric Toothbrush', 'Rechargeable electric toothbrush with timer', 49.99, 70, 7, 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=400'),
('Massage Gun', 'Deep tissue massage gun with 6 heads', 119.99, 35, 7, 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400'),
('Face Serum', 'Vitamin C face serum for glowing skin', 29.99, 80, 7, 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400'),
('Electric Shaver', 'Rechargeable electric shaver for men', 59.99, 55, 7, 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=400'),

-- Automotive (Category 8)
('Car Phone Mount', 'Universal magnetic car phone holder', 19.99, 120, 8, 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=400'),
('Dash Camera', 'Full HD dash cam with night vision', 89.99, 50, 8, 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400'),
('Car Vacuum Cleaner', 'Portable car vacuum with strong suction', 39.99, 65, 8, 'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=400'),
('Tire Pressure Gauge', 'Digital tire pressure gauge with LED display', 14.99, 100, 8, 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400'),

-- Food & Beverages (Category 9)
('Organic Coffee Beans', 'Premium organic coffee beans 1lb bag', 24.99, 90, 9, 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400'),
('Green Tea Box', 'Organic green tea 100 bags', 14.99, 110, 9, 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400'),
('Protein Powder', 'Whey protein powder chocolate flavor 2lbs', 39.99, 75, 9, 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400'),
('Olive Oil', 'Extra virgin olive oil 500ml bottle', 19.99, 85, 9, 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400'),
('Dark Chocolate Box', 'Premium dark chocolate gift box', 19.99, 90, 9, 'https://images.unsplash.com/photo-1549007953-2f2dc0b24019?w=400'),

-- Office Supplies (Category 10)
('Notebook Set', 'Hardcover notebooks set of 3', 19.99, 95, 10, 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=400'),
('Pen Holder', 'Wooden desk organizer and pen holder', 24.99, 80, 10, 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400'),
('Stapler', 'Heavy-duty office stapler', 12.99, 120, 10, 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400'),
('Office Chair', 'Ergonomic office chair with lumbar support', 199.99, 20, 10, 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400'),
('Desk Organizer', 'Multi-compartment desk organizer', 29.99, 75, 10, 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400')
